services:
  app:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html/
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: project
      DB_USER: root
      DB_PASS: ""

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: project
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql

volumes:
  db_data:
